variables:
  sampling_rate: &sampling_rate 16000 
  mel_bins: &mel_bins 64
  latent_embed_dim: &latent_embed_dim 8
  hop_len: &hop_len 160

model:
  base_learning_rate: 1.0e-5
  target: adm.models.diffusion.sd_ddpm_scale_audioldm.LatentDiffusion
  params:
    linear_start: 0.0015 # 0.00085 
    linear_end: 0.0195 # 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    video_cond_len: 39
    first_stage_key: "mix_spec"
    cond_stage_key: "mix_video_feat"
    image_size: 64
    channels: 8
    cond_stage_trainable: true   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    mean_factor: -0.0942
    scale_factor: 0.43146 #0.18215 
    #scale_by_std: True
    use_ema: False
    # ckpt_path: "/mnt/petrelfs/tangshixiang/dyh/Diff-Foley/training/neuroband/pretrained_model/sd-v1-4-full-ema.ckpt" #"/mnt/petrelfs/tangshixiang/dyh/Diff-Foley/inference/diff_foley_ckpt/ldm_epoch240.ckpt"
    ignore_keys: ['first_stage_model']
    scheduler_config: # 10000 warmup steps
      target: adm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 2000 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-8 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: adm.modules.diffusionmodules.openai_unetmodel_audioldm_v2.UNetModel
      params:
        image_size: 64 # unused
        in_channels: 8
        out_channels: 8
        model_channels: 256
        attention_resolutions: [ 8, 4, 2 ] #[ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 3, 5 ]
        num_head_channels: 64
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 1024
        use_checkpoint: True
        legacy: True

    first_stage_config:
      base_learning_rate: 8.0e-06
      target: audioldm_train.modules.latent_encoder.autoencoder.AutoencoderKL
      params: 
        reload_from_ckpt: "data/checkpoints/vae_mel_16k_64bins.ckpt"
        sampling_rate: *sampling_rate
        batchsize: 4
        monitor: val/rec_loss
        image_key: fbank
        subband: 1
        embed_dim: *latent_embed_dim
        time_shuffle: 1
        lossconfig:
          target: audioldm_train.losses.LPIPSWithDiscriminator
          params:
            disc_start: 50001
            kl_weight: 1000.0
            disc_weight: 0.5
            disc_in_channels: 1
        ddconfig: 
          double_z: true
          mel_bins: *mel_bins # The frequency bins of mel spectrogram
          z_channels: 8
          resolution: 256
          downsample_time: false
          in_channels: 1
          out_ch: 1
          ch: 128 
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
    
    cond_stage_config:
      target: adm.modules.cond_stage.video_feat_encoder.Video_Feat_Encoder_Posembed
      params:
        origin_dim: 512
        embed_dim: 1024
        seq_len: 40

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 100
    num_workers: 8
    wrap: True
    train:
      target: adm.data.video_spec_dataset_audioldm.audio_video_spec_fullset_Dataset_Train
      params:
        dataset1:
          dataset_name: VGGSound
          data_dir: /workspace/data_dir/USB_data/dyh_data/training_data/data_dir #/dataset/VGGSound
          video_dir: /workspace/data_dir/USB_data/dyh_data/training_data/video_dir #/dataset/VGGSound           # Not Necessary Except for Inference
          split_txt_path: /workspace/data_dir/USB_data/dyh_data/training_data #/dataset/VGGSound

        feat_type: CAVP_feat
        sr: *sampling_rate
        duration: 10
        truncate: 158720
        hop_len: *hop_len
        fps: 4

    validation:
      target: adm.data.video_spec_dataset_audioldm.audio_video_spec_fullset_Dataset_Valid #adm.data.video_spec_fullset_contrastive_concat_vgg_audioset_w_music.audio_video_spec_fullset_Dataset_Valid
      params:
        dataset1:
          dataset_name: VGGSound
          data_dir: /workspace/data_dir/USB_data/dyh_data/training_data/data_dir #/dataset/VGGSound
          video_dir: /workspace/data_dir/USB_data/dyh_data/training_data/video_dir #/dataset/VGGSound           # Not Necessary Except for Inference
          split_txt_path: /workspace/data_dir/USB_data/dyh_data/training_data #/dataset/VGGSound

        feat_type: CAVP_feat
        sr: *sampling_rate
        duration: 10
        truncate: 158720
        hop_len: *hop_len
        fps: 4

checkpoint:
  save_every_n_epochs: 4


callback:
  logger_name: sound_logger
  target: adm.logger.SoundLogger_concat_fullset
  params: 
    train_batch_frequency: 1000
    val_batch_frequency: 1000
    max_sound_num: 6
    sr: 16000
    fps: 4
    size_len: 248
    guidance_scale: 6.5
  


